// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fastLiclust
int fastLiclust(IntegerMatrix& linkmat, NumericVector& sim, IntegerVector& weights);
RcppExport SEXP fastliclust_fastLiclust(SEXP linkmatSEXP, SEXP simSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix& >::type linkmat(linkmatSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type sim(simSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type weights(weightsSEXP);
    __result = Rcpp::wrap(fastLiclust(linkmat, sim, weights));
    return __result;
END_RCPP
}

