// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fastLiclust
int fastLiclust(IntegerMatrix& linkmat, NumericVector& sim, IntegerVector& weights, double disconnect);
RcppExport SEXP fastliclust_fastLiclust(SEXP linkmatSEXP, SEXP simSEXP, SEXP weightsSEXP, SEXP disconnectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix& >::type linkmat(linkmatSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type sim(simSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type disconnect(disconnectSEXP);
    rcpp_result_gen = Rcpp::wrap(fastLiclust(linkmat, sim, weights, disconnect));
    return rcpp_result_gen;
END_RCPP
}
