# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLiclust <- function(linkmat, sim, weights) {
    .Call('fastliclust_fastLiclust', PACKAGE = 'fastliclust', linkmat, sim, weights)
}
